# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-02-20 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentinelStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='SentinelStore2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
