# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-02-20 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentinelStore2',
        ),
    ]
