# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-21 21:28
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_delete_sentinelstore2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentinelstore',
            name='WW3',
            field=jsonfield.fields.JSONField(default=' '),
            preserve_default=False,
        ),
    ]
