# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-21 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_sentinelstore_ww3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentinelstore',
            old_name='WW3',
            new_name='ww3',
        ),
    ]
